name: Main Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  call-request-ci:
    uses: iam-rajeshmrk/ghac-reusable-workflow/.github/workflows/reusable_workflow.yml@main
    with:
      node-version: ‘${{vars.node_version}}’
      run-tests: true
